Sort task closes #1
Howe251/DatabaseManagment pull request #2
Opened 2021-10-10 15:06 UTC by Howe251

Выполнено задание по созданию массива и его сортировке

2021-10-18 17:34 UTC, MarinaPaley requested changes

2021-10-18 17:34 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +    }
в отдельную функцию

2021-10-18 17:34 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +        cout << i+1 << ": " << values[i] << "\n";
в отдельную функцию

2021-10-18 17:34 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +        swap(values[stInd], values[maxIndex]);
в отдельную функцию

2021-10-18 17:34 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +        cout << i + 1 << ": " << values[i] << "\n";
в отдельную функцию

2021-10-20 13:53 UTC, MarinaPaley requested changes

2021-10-20 13:53 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +int sort(int size, int values[]) {
Функцию объявляете до `main()`, инициализируете после

2021-10-20 13:53 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +int sort(int size, int values[]) {
`int sort(const std::size_t size, int* values)`;

2021-10-20 13:53 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +    for (int stInd = 0; stInd < size - 1; stInd++)
`int std::size_t i`

2021-10-20 13:53 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +    cin >> size;
узнайте, `size > 0?`

2021-10-20 14:07 UTC, MarinaPaley requested changes
не надо `size_t`

2021-10-28 23:31 UTC, MarinaPaley requested changes

2021-10-28 23:31 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +int setSize(int *size);
к каждой функции нужна документация

2021-10-28 23:31 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +Главная функция
да, а что она возвращает?

2021-10-28 23:31 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +    setSize(&size);             // Определить размер массива
`const auto size = getSize()`;

2021-10-28 23:31 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +*/
вся документация располагается сверху при объявлении функции

2021-10-28 23:31 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +int setSize(int *size) {
не нужно передавать параметр, нужно его возвращать
`size_t getSize()`

2021-10-28 23:31 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +    {
в функции объявить локальную переменную типа `int` для возможности проверки. В случае успеха возвращать локальную переменную

2021-10-28 23:31 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +    for (int stInd = 0; stInd < size - 1; stInd++)
после того, как размер массива установлен, используйте тип `size_t`, для установки размера используйте тип `int`, чтобы узнать, не меньше ли он нуля

2021-10-28 23:39 UTC, Howe251 commented on ConsoleApplication1/ConsoleApplication1.cpp
> +int setSize(int *size) {
Мы же на паре договорились не использовать size_t

2021-11-03 13:46 UTC, MarinaPaley approved these changes

2021-11-03 13:46 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +    _getch();
`cin.get();`

2021-11-03 13:46 UTC, MarinaPaley commented on ConsoleApplication1/ConsoleApplication1.cpp
> +#include <conio.h>
не нужно

2021-11-03 14:41 UTC, merged